# Generated by Django 6.0.4 on 2026-05-03 07:10

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='marketing', max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField(default='')),
                ('senderEmail', models.CharField(default='', max_length=255)),
                ('senderName', models.CharField(default='', max_length=255)),
                ('recipientCount', models.IntegerField(default=0)),
                ('deliveredCount', models.IntegerField(default=0)),
                ('failedCount', models.IntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('scheduledAt', models.DateTimeField(blank=True, null=True)),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('createdById', models.CharField(default='', max_length=30)),
                ('segment', models.CharField(default='all', max_length=100)),
            ],
            options={
                'db_table': 'communications_emailcampaign',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(default='', max_length=500)),
                ('content', models.TextField(default='')),
                ('type', models.CharField(default='marketing', max_length=50)),
                ('variables', models.TextField(default='[]')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'communications_emailtemplate',
            },
        ),
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='marketing', max_length=50)),
                ('message', models.TextField(default='')),
                ('senderNumber', models.CharField(default='', max_length=50)),
                ('recipientCount', models.IntegerField(default=0)),
                ('deliveredCount', models.IntegerField(default=0)),
                ('failedCount', models.IntegerField(default=0)),
                ('pendingCount', models.IntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('scheduledAt', models.DateTimeField(blank=True, null=True)),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('createdById', models.CharField(default='', max_length=30)),
                ('segment', models.CharField(default='all', max_length=100)),
                ('filterJson', models.TextField(default='{}')),
                ('costPerSms', models.FloatField(default=35)),
                ('totalCost', models.FloatField(default=0)),
                ('template', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'communications_smscampaign',
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(default='')),
                ('type', models.CharField(default='marketing', max_length=50)),
                ('variables', models.TextField(default='[]')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'communication_smstemplate',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(default='', max_length=500)),
                ('content', models.TextField(default='')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('errorMessage', models.TextField(default='')),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('campaignId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communications.emailcampaign')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailLogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications_emaillog',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(default='')),
                ('type', models.CharField(default='info', max_length=50)),
                ('isRead', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications_notification',
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(default='')),
                ('type', models.CharField(default='marketing', max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('provider', models.CharField(default='kavenegar', max_length=50)),
                ('messageId', models.CharField(default='', max_length=100)),
                ('cost', models.FloatField(default=35)),
                ('errorMessage', models.TextField(default='')),
                ('retryCount', models.IntegerField(default=0)),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('campaignId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communications.smscampaign')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smsLogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications_smslog',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=500)),
                ('category', models.CharField(default='general', max_length=50)),
                ('status', models.CharField(default='open', max_length=50)),
                ('priority', models.CharField(default='normal', max_length=50)),
                ('department', models.CharField(default='support', max_length=50)),
                ('assignedTo', models.CharField(default='', max_length=30)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(default='')),
                ('slaDeadline', models.DateTimeField(blank=True, null=True)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
                ('firstReplyAt', models.DateTimeField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportTickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications_supportticket',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('chatId', models.CharField(default='', max_length=100)),
                ('telegramUsername', models.CharField(default='', max_length=100)),
                ('telegramId', models.CharField(default='', max_length=100)),
                ('isLinked', models.BooleanField(default=True)),
                ('linkedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegramUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications_telegramuser',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('isAdmin', models.BooleanField(default=False)),
                ('isInternal', models.BooleanField(default=False)),
                ('attachments', models.TextField(default='[]')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketMessages', to=settings.AUTH_USER_MODEL)),
                ('ticketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.supportticket')),
            ],
            options={
                'db_table': 'communications_ticketmessage',
            },
        ),
    ]
