apiVersion: v1
kind: ServiceAccount
metadata:
  name: zaringold-app
  namespace: zaringold
  labels:
    app.kubernetes.io/name: zaringold
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: zaringold
automountServiceAccountToken: false
