# Generated by Django 6.0.4 on 2026-05-03 07:10

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(default='Shield', max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('sortOrder', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'insurance_insurancecategory',
            },
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('logo', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('isActive', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'insurance_insuranceprovider',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(default='')),
                ('coverageType', models.CharField(default='', max_length=100)),
                ('premiumMonthly', models.FloatField(default=0)),
                ('premiumYearly', models.FloatField(default=0)),
                ('coverageAmount', models.FloatField(default=0)),
                ('deductible', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('sortOrder', models.IntegerField(default=0)),
                ('features', models.TextField(default='[]')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.insurancecategory')),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.insuranceprovider')),
            ],
            options={
                'db_table': 'insurance_insuranceplan',
            },
        ),
        migrations.CreateModel(
            name='InsuranceOrder',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('premiumAmount', models.FloatField()),
                ('coverageAmount', models.FloatField()),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('policyNumber', models.CharField(default='', max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insuranceOrders', to=settings.AUTH_USER_MODEL)),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='insurance.insuranceplan')),
            ],
            options={
                'db_table': 'insurance_insuranceorder',
            },
        ),
    ]
