# Generated by Django 6.0.4 on 2026-05-03 07:06

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('userId', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('userAgent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_audit_log',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('blockedBy', models.CharField(blank=True, max_length=30, null=True)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_blocked_ip',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='GoldReserve',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('totalGrams', models.FloatField(default=0)),
                ('todayAddedGrams', models.FloatField(default=0)),
                ('reserveRatio', models.FloatField(default=1.0)),
                ('lastAuditDate', models.DateField(blank=True, null=True)),
                ('auditFirm', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'core_gold_reserve',
            },
        ),
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('sectionId', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('icon', models.CharField(default='Layout', max_length=50)),
                ('isVisible', models.BooleanField(default=True)),
                ('sortOrder', models.IntegerField(default=0)),
                ('settings', models.TextField(default='{}')),
            ],
            options={
                'db_table': 'core_landing_section',
                'ordering': ['sortOrder'],
            },
        ),
        migrations.CreateModel(
            name='LoanSetting',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_loan_setting',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('originalName', models.CharField(blank=True, default='', max_length=255)),
                ('mimeType', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.BigIntegerField(default=0)),
                ('url', models.URLField(max_length=500)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('folder', models.CharField(default='general', max_length=100)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploadedBy', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'core_media',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_security_config',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('userId', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('userAgent', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('riskScore', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_security_event',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('group', models.CharField(db_index=True, default='general', max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'core_system_setting',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, default='')),
                ('type', models.CharField(default='text', max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sortOrder', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'core_site_setting',
                'ordering': ['group', 'sortOrder'],
                'unique_together': {('group', 'key')},
            },
        ),
    ]
