# Generated by Django 6.0.4 on 2026-05-03 07:45

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorSubmission',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(default='')),
                ('submissionType', models.CharField(default='article', max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('adminNote', models.TextField(default='')),
                ('reviewedBy', models.CharField(default='', max_length=30)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.TextField(default='[]')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorSubmissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_panel_creatorsubmission',
            },
        ),
    ]
