# Generated by Django 6.0.4 on 2026-05-03 07:10

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarServiceCategory',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(default='Car', max_length=50)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'services_carservicecategory',
            },
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(default='', max_length=50)),
                ('plateNumber', models.CharField(default='', max_length=50)),
                ('fuelType', models.CharField(default='gasoline', max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_usercar',
            },
        ),
        migrations.CreateModel(
            name='CarServiceOrder',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('description', models.TextField(default='')),
                ('scheduledAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('cost', models.FloatField(default=0)),
                ('trackingCode', models.CharField(default='', max_length=100)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.carservicecategory')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carServiceOrders', to=settings.AUTH_USER_MODEL)),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceOrders', to='services.usercar')),
            ],
            options={
                'db_table': 'services_carserviceorder',
            },
        ),
        migrations.CreateModel(
            name='UtilityPayment',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='electricity', max_length=50)),
                ('billId', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('trackingCode', models.CharField(default='', max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilityPayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_utilitypayment',
            },
        ),
    ]
