# Generated by Django 6.0.4 on 2026-05-03 07:06

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('module', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'authentication_permission',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('permissions', models.TextField(default='[]')),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('isSystem', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'authentication_role',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('fullName', models.CharField(blank=True, default='', max_length=200)),
                ('isVerified', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isFrozen', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(default='user', max_length=50)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('referredBy', models.CharField(blank=True, max_length=30, null=True)),
                ('referralCode', models.CharField(max_length=50, unique=True)),
                ('userLevel', models.CharField(default='bronze', max_length=50)),
                ('levelUpgradedAt', models.DateTimeField(blank=True, null=True)),
                ('lastLoginAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'authentication_user',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='KYCRequest',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('idCardImage', models.CharField(blank=True, default='', max_length=500)),
                ('idCardBackImage', models.CharField(blank=True, default='', max_length=500)),
                ('selfieImage', models.CharField(blank=True, default='', max_length=500)),
                ('bankCardImage', models.CharField(blank=True, default='', max_length=500)),
                ('verificationVideo', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('adminNote', models.TextField(blank=True, default='')),
                ('reviewedBy', models.CharField(blank=True, max_length=30, null=True)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('userId', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authentication_kyc_request',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('reset_password', 'Reset Password'), ('verify_phone', 'Verify Phone')], default='login', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('maxAttempts', models.IntegerField(default=5)),
                ('expiresAt', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authentication_otp_code',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('nationalId', models.CharField(blank=True, default='', max_length=20)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('iban', models.CharField(blank=True, default='', max_length=30)),
                ('bankCard', models.CharField(blank=True, default='', max_length=20)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('postalCode', models.CharField(blank=True, default='', max_length=20)),
                ('userId', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authentication_profile',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('userAgent', models.TextField(blank=True, default='')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authentication_user_activity',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('device', models.CharField(blank=True, default='', max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('userAgent', models.TextField(blank=True, default='')),
                ('expiresAt', models.DateTimeField()),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authentication_user_session',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('permissionId', models.ForeignKey(db_column='permissionId', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.permission')),
                ('roleId', models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.role')),
            ],
            options={
                'db_table': 'authentication_role_permission',
                'unique_together': {('roleId', 'permissionId')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('assignedBy', models.CharField(blank=True, max_length=30, null=True)),
                ('assignedAt', models.DateTimeField(auto_now_add=True)),
                ('roleId', models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='authentication.role')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authentication_user_role',
                'unique_together': {('userId', 'roleId')},
            },
        ),
    ]
