# Generated by Django 6.0.4 on 2026-05-03 07:10

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldLoan',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('amountRequested', models.FloatField()),
                ('goldCollateral', models.FloatField()),
                ('goldPriceAtLoan', models.FloatField()),
                ('ltvRatio', models.FloatField(default=0.7)),
                ('interestRate', models.FloatField(default=0.05)),
                ('durationDays', models.IntegerField(default=30)),
                ('amountApproved', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('adminNote', models.TextField(default='')),
                ('reviewedBy', models.CharField(default='', max_length=30)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('approvedAt', models.DateTimeField(blank=True, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('repaidAmount', models.FloatField(default=0)),
                ('penaltyAmount', models.FloatField(default=0)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goldLoans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_goldloan',
            },
        ),
        migrations.CreateModel(
            name='GoldWallet',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('goldGrams', models.FloatField(default=0)),
                ('frozenGold', models.FloatField(default=0)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goldWallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_goldwallet',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('penalty', models.FloatField(default=0)),
                ('method', models.CharField(default='wallet', max_length=50)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('description', models.TextField(default='')),
                ('loanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='wallet.goldloan')),
            ],
            options={
                'db_table': 'wallet_loanrepayment',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('authority', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField()),
                ('description', models.CharField(default='شارژ کیف پول زرین گلد', max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('provider', models.CharField(default='zarinpal', max_length=50)),
                ('refId', models.CharField(default='', max_length=255)),
                ('cardPan', models.CharField(default='', max_length=50)),
                ('fee', models.FloatField(default=0)),
                ('verifiedAt', models.DateTimeField(blank=True, null=True)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_payment',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField(default=0)),
                ('frozenBalance', models.FloatField(default=0)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_wallet',
            },
        ),
    ]
