# Generated by Django 6.0.4 on 2026-05-03 07:06

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('buyPrice', models.FloatField()),
                ('sellPrice', models.FloatField()),
                ('marketPrice', models.FloatField()),
                ('ouncePrice', models.FloatField()),
                ('spread', models.FloatField(default=0)),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('isManual', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gold_gold_price',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('interval', models.CharField(default='1h', max_length=10)),
                ('openPrice', models.FloatField(default=0)),
                ('highPrice', models.FloatField(default=0)),
                ('lowPrice', models.FloatField(default=0)),
                ('closePrice', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'gold_price_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=20)),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=20)),
                ('targetPrice', models.FloatField()),
                ('isActive', models.BooleanField(default=True)),
                ('isTriggered', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gold_price_alert',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('reward', 'Reward'), ('fee', 'Fee')], max_length=20)),
                ('amountFiat', models.FloatField(default=0)),
                ('amountGold', models.FloatField(default=0)),
                ('fee', models.FloatField(default=0)),
                ('goldPrice', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('referenceId', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('toUserId', models.CharField(blank=True, max_length=30, null=True)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gold_transaction',
                'ordering': ['-createdAt'],
            },
        ),
    ]
