# Generated by Django 6.0.4 on 2026-05-03 07:10

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyWallet',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'social_familywallet',
            },
        ),
        migrations.CreateModel(
            name='GiftTransfer',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('goldMg', models.FloatField()),
                ('message', models.TextField(default='')),
                ('occasion', models.CharField(default='', max_length=100)),
                ('giftCardStyle', models.CharField(default='birthday', max_length=50)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('scheduledAt', models.DateTimeField(blank=True, null=True)),
                ('openedAt', models.DateTimeField(blank=True, null=True)),
                ('receiverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedGifts', to=settings.AUTH_USER_MODEL)),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentGifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_gifttransfer',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('rewardType', models.CharField(default='cash', max_length=50)),
                ('rewardAmount', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('claimedAt', models.DateTimeField(blank=True, null=True)),
                ('referredId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referredByRel', to=settings.AUTH_USER_MODEL)),
                ('referrerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_referral',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('postType', models.CharField(default='trade', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('isAnonymous', models.BooleanField(default=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialPosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_socialpost',
            },
        ),
        migrations.CreateModel(
            name='FamilyWalletMember',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='member', max_length=50)),
                ('contribution', models.FloatField(default=0)),
                ('canWithdraw', models.BooleanField(default=False)),
                ('joinedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familyWallets', to=settings.AUTH_USER_MODEL)),
                ('walletId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social.familywallet')),
            ],
            options={
                'db_table': 'social_familywalletmember',
                'unique_together': {('walletId', 'userId')},
            },
        ),
    ]
