# Generated by Django 6.0.4 on 2026-05-03 07:10

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(default='')),
                ('color', models.CharField(default='#D4AF37', max_length=20)),
                ('icon', models.CharField(default='BookOpen', max_length=50)),
                ('sortOrder', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'content_blogcategory',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'content_blogtag',
            },
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(default='')),
                ('seoTitle', models.CharField(default='', max_length=500)),
                ('seoDesc', models.CharField(default='', max_length=500)),
                ('isPublished', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'content_cmspage',
            },
        ),
        migrations.CreateModel(
            name='SmsConfig',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='kavenegar', max_length=50)),
                ('apiKey', models.CharField(default='', max_length=500)),
                ('senderNumber', models.CharField(default='', max_length=50)),
                ('otpTemplate', models.CharField(default='', max_length=100)),
                ('lastTestAt', models.DateTimeField(blank=True, null=True)),
                ('lastTestOk', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_smsconfig',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('content', models.TextField(default='')),
                ('excerpt', models.TextField(default='')),
                ('featuredImage', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('seoTitle', models.CharField(default='', max_length=500)),
                ('seoDesc', models.CharField(default='', max_length=500)),
                ('readTime', models.IntegerField(default=1)),
                ('isFeatured', models.BooleanField(default=False)),
                ('viewCount', models.IntegerField(default=0)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogPosts', to=settings.AUTH_USER_MODEL)),
                ('categoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.blogcategory')),
            ],
            options={
                'db_table': 'content_blogpost',
            },
        ),
        migrations.CreateModel(
            name='CMSComponent',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('props', models.TextField(default='')),
                ('pageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='content.cmspage')),
            ],
            options={
                'db_table': 'content_cmscomponent',
            },
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogPostTags', to='content.blogpost')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogPostTags', to='content.blogtag')),
            ],
            options={
                'db_table': 'content_blogposttag',
                'unique_together': {('postId', 'tagId')},
            },
        ),
    ]
