apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "zaringold.labels" . | nindent 4 }}
    app.kubernetes.io/environment: {{ .Values.config.nodeEnv }}
{{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
