import { NextResponse } from 'next/server'
import { db } from '@/lib/db'

export async function GET() {
  try {
    // Check if data already exists
    const existingProviders = await db.insuranceProvider.count()
    if (existingProviders > 0) {
      return NextResponse.json({
        success: true,
        message: 'داده‌ها از قبل وجود دارند',
        seeded: false,
      })
    }

    // Create providers
    const providers = await db.insuranceProvider.createMany({
      data: [
        {
          name: 'بیمه پاسارگاد',
          nameEn: 'Parsian Insurance',
          logo: '/images/insurance/parsian.svg',
          commissionRate: 5,
          commissionFixed: 0,
          sortOrder: 1,
        },
        {
          name: 'بیمه ایران',
          nameEn: 'Iran Insurance',
          logo: '/images/insurance/iran.svg',
          commissionRate: 4,
          commissionFixed: 0,
          sortOrder: 2,
        },
        {
          name: 'بیمه آسیا',
          nameEn: 'Asia Insurance',
          logo: '/images/insurance/asia.svg',
          commissionRate: 6,
          commissionFixed: 0,
          sortOrder: 3,
        },
        {
          name: 'بیمه البرز',
          nameEn: 'Alborz Insurance',
          logo: '/images/insurance/alborz.svg',
          commissionRate: 4.5,
          commissionFixed: 0,
          sortOrder: 4,
        },
      ],
    })

    // Get provider IDs
    const providerList = await db.insuranceProvider.findMany({
      orderBy: { sortOrder: 'asc' },
    })
    const [parsian, iran, asia, alborz] = providerList

    // Create categories
    const categories = await db.insuranceCategory.createMany({
      data: [
        {
          name: 'بیمه شخص ثالث',
          nameEn: 'Third Party Auto Insurance',
          slug: 'third-party-auto',
          icon: 'Car',
          description: 'بیمه اجباری برای تمامی وسایل نقلیه موتوری',
          descriptionEn: 'Mandatory insurance for all motor vehicles',
          color: '#2563EB',
          sortOrder: 1,
          hasSubtypes: true,
          subtypes: JSON.stringify([
            { slug: 'personal', name: 'شخصی', nameEn: 'Personal' },
            { slug: 'motorcycle', name: 'موتورسیکلت', nameEn: 'Motorcycle' },
            { slug: 'public', name: 'عمومی', nameEn: 'Public' },
          ]),
          formFields: JSON.stringify([
            { key: 'plateNumber', label: 'شماره پلاک', labelEn: 'Plate Number', type: 'text', required: true },
            { key: 'chassisNumber', label: 'شماره شاسی', labelEn: 'Chassis Number', type: 'text', required: true },
            { key: 'carModel', label: 'مدل خودرو', labelEn: 'Car Model', type: 'text', required: true },
            { key: 'carYear', label: 'سال ساخت', labelEn: 'Year', type: 'number', required: true },
          ]),
          providerId: parsian.id,
        },
        {
          name: 'بیمه بدنه',
          nameEn: 'Body / Collision Insurance',
          slug: 'body-insurance',
          icon: 'ShieldCheck',
          description: 'پوشش آسیب‌های بدنه در تصادفات',
          descriptionEn: 'Coverage for body damage in accidents',
          color: '#059669',
          sortOrder: 2,
          hasSubtypes: false,
          formFields: JSON.stringify([
            { key: 'plateNumber', label: 'شماره پلاک', labelEn: 'Plate Number', type: 'text', required: true },
            { key: 'carModel', label: 'مدل خودرو', labelEn: 'Car Model', type: 'text', required: true },
            { key: 'carYear', label: 'سال ساخت', labelEn: 'Year', type: 'number', required: true },
            { key: 'carValue', label: 'ارزش خودرو (تومان)', labelEn: 'Car Value (Toman)', type: 'number', required: true },
          ]),
          providerId: iran.id,
        },
        {
          name: 'بیمه موتورسیکلت',
          nameEn: 'Motorcycle Insurance',
          slug: 'motorcycle-insurance',
          icon: 'Bike',
          description: 'بیمه شخص ثالث و بدنه موتورسیکلت',
          descriptionEn: 'Third party and body insurance for motorcycles',
          color: '#7C3AED',
          sortOrder: 3,
          hasSubtypes: false,
          formFields: JSON.stringify([
            { key: 'plateNumber', label: 'شماره پلاک', labelEn: 'Plate Number', type: 'text', required: true },
            { key: 'motorcycleModel', label: 'مدل موتور', labelEn: 'Motorcycle Model', type: 'text', required: true },
            { key: 'motorcycleYear', label: 'سال ساخت', labelEn: 'Year', type: 'number', required: true },
          ]),
          providerId: parsian.id,
        },
        {
          name: 'بیمه درمان',
          nameEn: 'Health Insurance',
          slug: 'health-insurance',
          icon: 'HeartPulse',
          description: 'پوشش هزینه‌های پزشکی و درمانی',
          descriptionEn: 'Coverage for medical and treatment expenses',
          color: '#DC2626',
          sortOrder: 4,
          hasSubtypes: true,
          subtypes: JSON.stringify([
            { slug: 'basic', name: 'پایه', nameEn: 'Basic' },
            { slug: 'complementary', name: 'تکمیلی', nameEn: 'Complementary' },
            { slug: 'dental', name: 'دندانپزشکی', nameEn: 'Dental' },
          ]),
          formFields: JSON.stringify([
            { key: 'age', label: 'سن', labelEn: 'Age', type: 'number', required: true },
            { key: 'gender', label: 'جنسیت', labelEn: 'Gender', type: 'select', required: true, options: ['male', 'female'] },
            { key: 'preConditions', label: 'بیماری‌های قبلی', labelEn: 'Pre-existing Conditions', type: 'text', required: false },
          ]),
          providerId: asia.id,
        },
        {
          name: 'بیمه مسافرتی',
          nameEn: 'Travel Insurance',
          slug: 'travel-insurance',
          icon: 'Plane',
          description: 'پوشش حوادث و بیماری در سفرهای خارجی',
          descriptionEn: 'Coverage for accidents and illness during foreign trips',
          color: '#0891B2',
          sortOrder: 5,
          hasSubtypes: false,
          formFields: JSON.stringify([
            { key: 'destination', label: 'مقصد', labelEn: 'Destination', type: 'text', required: true },
            { key: 'tripDays', label: 'تعداد روز سفر', labelEn: 'Trip Duration (Days)', type: 'number', required: true },
            { key: 'tripPurpose', label: 'هدف سفر', labelEn: 'Trip Purpose', type: 'select', required: true, options: ['tourism', 'business', 'study', 'treatment'] },
          ]),
          providerId: alborz.id,
        },
        {
          name: 'بیمه آتش‌سوزی',
          nameEn: 'Fire Insurance',
          slug: 'fire-insurance',
          icon: 'Flame',
          description: 'پوشش خسارت ناشی از آتش‌سوزی و حوادث مرتبط',
          descriptionEn: 'Coverage for fire damage and related incidents',
          color: '#EA580C',
          sortOrder: 6,
          hasSubtypes: false,
          formFields: JSON.stringify([
            { key: 'buildingType', label: 'نوع ساختمان', labelEn: 'Building Type', type: 'select', required: true, options: ['apartment', 'villa', 'commercial', 'industrial'] },
            { key: 'buildingArea', label: 'زیربنا (مترمربع)', labelEn: 'Building Area (sqm)', type: 'number', required: true },
            { key: 'buildingValue', label: 'ارزش ساختمان (تومان)', labelEn: 'Building Value (Toman)', type: 'number', required: true },
          ]),
          providerId: iran.id,
        },
        {
          name: 'بیمه عمر',
          nameEn: 'Life Insurance',
          slug: 'life-insurance',
          icon: 'Heart',
          description: 'پوشش سرمایه‌گذاری و پس‌انداز بلندمدت',
          descriptionEn: 'Long-term investment and savings coverage',
          color: '#BE185D',
          sortOrder: 7,
          hasSubtypes: true,
          subtypes: JSON.stringify([
            { slug: 'term', name: 'عمر زمانی', nameEn: 'Term Life' },
            { slug: 'whole', name: 'عمر کامل', nameEn: 'Whole Life' },
            { slug: 'universal', name: 'فراگیر', nameEn: 'Universal' },
          ]),
          formFields: JSON.stringify([
            { key: 'age', label: 'سن', labelEn: 'Age', type: 'number', required: true },
            { key: 'gender', label: 'جنسیت', labelEn: 'Gender', type: 'select', required: true, options: ['male', 'female'] },
            { key: 'smoker', label: 'سیگاری', labelEn: 'Smoker', type: 'select', required: true, options: ['yes', 'no'] },
            { key: 'coverageAmount', label: 'مبلغ پوشش (تومان)', labelEn: 'Coverage Amount (Toman)', type: 'number', required: true },
          ]),
          providerId: parsian.id,
        },
        {
          name: 'بیمه مسئولیت',
          nameEn: 'Liability Insurance',
          slug: 'liability-insurance',
          icon: 'Scale',
          description: 'پوشش مسئولیت حرفه‌ای و عمومی',
          descriptionEn: 'Professional and general liability coverage',
          color: '#4338CA',
          sortOrder: 8,
          hasSubtypes: false,
          formFields: JSON.stringify([
            { key: 'businessType', label: 'نوع کسب‌وکار', labelEn: 'Business Type', type: 'text', required: true },
            { key: 'employeesCount', label: 'تعداد کارکنان', labelEn: 'Employees Count', type: 'number', required: true },
            { key: 'annualRevenue', label: 'درآمد سالانه (تومان)', labelEn: 'Annual Revenue (Toman)', type: 'number', required: false },
          ]),
          providerId: alborz.id,
        },
      ],
    })

    // Get category IDs
    const categoryList = await db.insuranceCategory.findMany({
      orderBy: { sortOrder: 'asc' },
    })
    const [thirdParty, body, motorcycle, health, travel, fire, life, liability] = categoryList

    // Create plans - 2-3 per category from different providers
    const plans = await db.insurancePlan.createMany({
      data: [
        // ── Third Party Auto ──
        {
          providerId: parsian.id,
          categoryId: thirdParty.id,
          name: 'شخص ثالث پایه - سواری',
          nameEn: 'Basic Third Party - Sedan',
          description: 'حداقل پوشش قانونی شخص ثالث برای خودروهای سواری',
          descriptionEn: 'Minimum legal third party coverage for sedans',
          basePrice: 4800000,
          sellingPrice: 5100000,
          commissionType: 'percentage',
          commissionValue: 5,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 1000000000,
          coverages: JSON.stringify([
            { title: 'ديات فوت ناشی از حادثه', titleEn: 'Death compensation', amount: 1000000000, description: 'پوشش کامل دیات فوت' },
            { title: 'ديات نقص عضو', titleEn: 'Disability compensation', amount: 500000000, description: 'پوشش نقص عضو' },
            { title: 'خسارت مالی اشخاص ثالث', titleEn: 'Property damage', amount: 50000000, description: 'حداکثر ۵۰ میلیون' },
          ]),
          minAge: 18,
          maxAge: 70,
          sortOrder: 1,
        },
        {
          providerId: iran.id,
          categoryId: thirdParty.id,
          name: 'شخص ثالث طلایی - سواری',
          nameEn: 'Gold Third Party - Sedan',
          description: 'پوشش کامل شخص ثالث با حداکثر دیات و پوشش مالی بالا',
          descriptionEn: 'Full third party coverage with max compensation',
          basePrice: 7200000,
          sellingPrice: 7500000,
          commissionType: 'percentage',
          commissionValue: 4,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 2000000000,
          coverages: JSON.stringify([
            { title: 'ديات فوت', titleEn: 'Death compensation', amount: 2000000000, description: 'پوشش کامل' },
            { title: 'ديات نقص عضو', titleEn: 'Disability compensation', amount: 1000000000, description: 'پوشش کامل' },
            { title: 'خسارت مالی', titleEn: 'Property damage', amount: 100000000, description: 'حداکثر ۱۰۰ میلیون' },
            { title: 'هزینه‌های درمانی', titleEn: 'Medical expenses', amount: 200000000, description: 'تا ۲۰۰ میلیون' },
          ]),
          minAge: 18,
          maxAge: 70,
          sortOrder: 2,
        },
        {
          providerId: alborz.id,
          categoryId: thirdParty.id,
          name: 'شخص ثالث اقتصادی',
          nameEn: 'Economy Third Party',
          description: 'پوشش شخص ثالث با قیمت مناسب',
          descriptionEn: 'Affordable third party coverage',
          basePrice: 4200000,
          sellingPrice: 4400000,
          commissionType: 'percentage',
          commissionValue: 4.5,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 700000000,
          coverages: JSON.stringify([
            { title: 'ديات فوت', titleEn: 'Death compensation', amount: 700000000, description: 'پوشش پایه' },
            { title: 'ديات نقص عضو', titleEn: 'Disability compensation', amount: 350000000, description: 'پوشش پایه' },
            { title: 'خسارت مالی', titleEn: 'Property damage', amount: 25000000, description: 'تا ۲۵ میلیون' },
          ]),
          minAge: 18,
          maxAge: 70,
          sortOrder: 3,
        },

        // ── Body Insurance ──
        {
          providerId: iran.id,
          categoryId: body.id,
          name: 'بیمه بدنه کامل',
          nameEn: 'Full Body Insurance',
          description: 'پوشش کامل خسارت بدنه شامل تصادف، سرقت، بلایای طبیعی',
          descriptionEn: 'Full body coverage including collision, theft, natural disasters',
          basePrice: 12000000,
          sellingPrice: 12800000,
          commissionType: 'percentage',
          commissionValue: 4,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 2000000000,
          coverages: JSON.stringify([
            { title: 'تصادف', titleEn: 'Collision', amount: 2000000000, description: 'پوشش کامل تصادفات' },
            { title: 'سرقت', titleEn: 'Theft', amount: 2000000000, description: 'سرقت کامل خودرو' },
            { title: 'بلایای طبیعی', titleEn: 'Natural disasters', amount: 2000000000, description: 'سیل، زلزله، طوفان' },
            { title: 'شیشه‌شکنی', titleEn: 'Glass breakage', amount: 50000000, description: 'بدون کسر فرانشیز' },
          ]),
          minAge: 18,
          maxAge: 70,
          sortOrder: 1,
        },
        {
          providerId: asia.id,
          categoryId: body.id,
          name: 'بیمه بدنه اقتصادی',
          nameEn: 'Economy Body Insurance',
          description: 'پوشش بدنه با قیمت مناسب - تصادف و سرقت',
          descriptionEn: 'Affordable body coverage - collision and theft',
          basePrice: 8500000,
          sellingPrice: 9000000,
          commissionType: 'percentage',
          commissionValue: 6,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 1000000000,
          coverages: JSON.stringify([
            { title: 'تصادف', titleEn: 'Collision', amount: 1000000000, description: 'پوشش تصادفات' },
            { title: 'سرقت', titleEn: 'Theft', amount: 1000000000, description: 'سرقت کامل' },
          ]),
          minAge: 18,
          maxAge: 70,
          sortOrder: 2,
        },

        // ── Motorcycle ──
        {
          providerId: parsian.id,
          categoryId: motorcycle.id,
          name: 'بیمه ثالث موتور - پایه',
          nameEn: 'Basic Motorcycle Third Party',
          description: 'حداقل پوشش قانونی برای موتورسیکلت',
          descriptionEn: 'Minimum legal coverage for motorcycles',
          basePrice: 1800000,
          sellingPrice: 1950000,
          commissionType: 'percentage',
          commissionValue: 5,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 500000000,
          coverages: JSON.stringify([
            { title: 'ديات فوت', titleEn: 'Death compensation', amount: 500000000, description: 'پوشش دیات' },
            { title: 'خسارت مالی', titleEn: 'Property damage', amount: 15000000, description: 'تا ۱۵ میلیون' },
          ]),
          minAge: 18,
          maxAge: 65,
          sortOrder: 1,
        },
        {
          providerId: alborz.id,
          categoryId: motorcycle.id,
          name: 'بیمه ثالث و بدنه موتور',
          nameEn: 'Motorcycle Third Party + Body',
          description: 'پوشش ثالث و بدنه موتورسیکلت',
          descriptionEn: 'Combined third party and body coverage',
          basePrice: 3500000,
          sellingPrice: 3700000,
          commissionType: 'percentage',
          commissionValue: 4.5,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 800000000,
          coverages: JSON.stringify([
            { title: 'ديات فوت', titleEn: 'Death compensation', amount: 500000000, description: 'پوشش دیات' },
            { title: 'خسارت بدنه', titleEn: 'Body damage', amount: 300000000, description: 'خسارت بدنه موتور' },
            { title: 'سرقت', titleEn: 'Theft', amount: 200000000, description: 'سرقت موتور' },
          ]),
          minAge: 18,
          maxAge: 65,
          sortOrder: 2,
        },

        // ── Health Insurance ──
        {
          providerId: asia.id,
          categoryId: health.id,
          name: 'بیمه درمان پایه',
          nameEn: 'Basic Health Insurance',
          description: 'پوشش درمانی پایه - ویزیت، آزمایش، دارو',
          descriptionEn: 'Basic health coverage - visits, tests, medication',
          basePrice: 3500000,
          sellingPrice: 3800000,
          commissionType: 'percentage',
          commissionValue: 6,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 50000000,
          coverages: JSON.stringify([
            { title: 'ویزیت پزشک', titleEn: 'Doctor visits', amount: 5000000, description: 'تا ۵ میلیون در سال' },
            { title: 'آزمایش و تصویربرداری', titleEn: 'Lab & imaging', amount: 10000000, description: 'تا ۱۰ میلیون' },
            { title: 'دارو', titleEn: 'Medication', amount: 8000000, description: 'تا ۸ میلیون' },
            { title: 'بستری', titleEn: 'Hospitalization', amount: 20000000, description: 'تا ۲۰ میلیون' },
          ]),
          minAge: 0,
          maxAge: 65,
          sortOrder: 1,
        },
        {
          providerId: parsian.id,
          categoryId: health.id,
          name: 'بیمه درمان تکمیلی طلایی',
          nameEn: 'Gold Complementary Health Insurance',
          description: 'بالاترین سطح پوشش درمانی - شامل اعمال جراحی',
          descriptionEn: 'Premium health coverage - including surgeries',
          basePrice: 8500000,
          sellingPrice: 9000000,
          commissionType: 'percentage',
          commissionValue: 5,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 200000000,
          coverages: JSON.stringify([
            { title: 'ویزیت پزشک', titleEn: 'Doctor visits', amount: 15000000, description: 'تا ۱۵ میلیون' },
            { title: 'آزمایش و تصویربرداری', titleEn: 'Lab & imaging', amount: 30000000, description: 'تا ۳۰ میلیون' },
            { title: 'دارو', titleEn: 'Medication', amount: 25000000, description: 'تا ۲۵ میلیون' },
            { title: 'بستری و جراحی', titleEn: 'Hospitalization & surgery', amount: 100000000, description: 'تا ۱۰۰ میلیون' },
            { title: 'دندانپزشکی', titleEn: 'Dental', amount: 15000000, description: 'تا ۱۵ میلیون' },
          ]),
          minAge: 0,
          maxAge: 65,
          sortOrder: 2,
        },
        {
          providerId: iran.id,
          categoryId: health.id,
          name: 'بیمه درمان خانواده',
          nameEn: 'Family Health Insurance',
          description: 'پوشش درمانی مناسب برای کل خانواده',
          descriptionEn: 'Affordable health coverage for the whole family',
          basePrice: 6000000,
          sellingPrice: 6400000,
          commissionType: 'percentage',
          commissionValue: 4,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 100000000,
          coverages: JSON.stringify([
            { title: 'ویزیت پزشک', titleEn: 'Doctor visits', amount: 10000000, description: 'تا ۱۰ میلیون' },
            { title: 'آزمایش', titleEn: 'Lab tests', amount: 15000000, description: 'تا ۱۵ میلیون' },
            { title: 'دارو', titleEn: 'Medication', amount: 15000000, description: 'تا ۱۵ میلیون' },
            { title: 'بستری', titleEn: 'Hospitalization', amount: 50000000, description: 'تا ۵۰ میلیون' },
          ]),
          minAge: 0,
          maxAge: 70,
          sortOrder: 3,
        },

        // ── Travel Insurance ──
        {
          providerId: alborz.id,
          categoryId: travel.id,
          name: 'بیمه مسافرتی اروپا',
          nameEn: 'Europe Travel Insurance',
          description: 'پوشش کامل برای سفر به کشورهای اروپایی',
          descriptionEn: 'Full coverage for European destinations',
          basePrice: 2500000,
          sellingPrice: 2800000,
          commissionType: 'percentage',
          commissionValue: 4.5,
          durationDays: 30,
          durationLabel: '30 روزه',
          durationLabelEn: '30 Days',
          coverageAmount: 500000000,
          coverages: JSON.stringify([
            { title: 'هزینه پزشکی', titleEn: 'Medical expenses', amount: 300000000, description: 'تا ۳۰۰ میلیون' },
            { title: 'انتقال پزشکی', titleEn: 'Medical evacuation', amount: 200000000, description: 'انتقال اورژانسی' },
            { title: 'تأخیر پرواز', titleEn: 'Flight delay', amount: 5000000, description: 'جبران تأخیر' },
            { title: 'گمشدگی چمدان', titleEn: 'Lost luggage', amount: 20000000, description: 'تا ۲۰ میلیون' },
          ]),
          minAge: 1,
          maxAge: 80,
          sortOrder: 1,
        },
        {
          providerId: parsian.id,
          categoryId: travel.id,
          name: 'بیمه مسافرتی ترکیه',
          nameEn: 'Turkey Travel Insurance',
          description: 'پوشش مناسب برای سفر به ترکیه',
          descriptionEn: 'Affordable coverage for Turkey trips',
          basePrice: 800000,
          sellingPrice: 900000,
          commissionType: 'percentage',
          commissionValue: 5,
          durationDays: 7,
          durationLabel: '7 روزه',
          durationLabelEn: '7 Days',
          coverageAmount: 100000000,
          coverages: JSON.stringify([
            { title: 'هزینه پزشکی', titleEn: 'Medical expenses', amount: 70000000, description: 'تا ۷۰ میلیون' },
            { title: 'انتقال پزشکی', titleEn: 'Medical evacuation', amount: 50000000, description: 'در صورت نیاز' },
            { title: 'تأخیر پرواز', titleEn: 'Flight delay', amount: 2000000, description: 'جبران تأخیر' },
          ]),
          minAge: 1,
          maxAge: 80,
          sortOrder: 2,
        },

        // ── Fire Insurance ──
        {
          providerId: iran.id,
          categoryId: fire.id,
          name: 'بیمه آتش‌سوزی مسکونی',
          nameEn: 'Residential Fire Insurance',
          description: 'پوشش آتش‌سوزی، زلزله و سیل برای منازل',
          descriptionEn: 'Fire, earthquake and flood coverage for homes',
          basePrice: 1500000,
          sellingPrice: 1650000,
          commissionType: 'percentage',
          commissionValue: 4,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 2000000000,
          coverages: JSON.stringify([
            { title: 'آتش‌سوزی', titleEn: 'Fire', amount: 2000000000, description: 'خسارت ناشی از آتش' },
            { title: 'زلزله', titleEn: 'Earthquake', amount: 2000000000, description: 'خسارت زلزله' },
            { title: 'سیل', titleEn: 'Flood', amount: 2000000000, description: 'خسارت سیل' },
            { title: 'انفجار', titleEn: 'Explosion', amount: 2000000000, description: 'خسارت انفجار' },
            { title: 'سرقت', titleEn: 'Theft', amount: 200000000, description: 'تا ۲۰۰ میلیون' },
          ]),
          minAge: 18,
          maxAge: 80,
          sortOrder: 1,
        },
        {
          providerId: asia.id,
          categoryId: fire.id,
          name: 'بیمه آتش‌سوزی تجاری',
          nameEn: 'Commercial Fire Insurance',
          description: 'پوشش آتش‌سوزی برای اماکن تجاری و صنعتی',
          descriptionEn: 'Fire coverage for commercial and industrial properties',
          basePrice: 5000000,
          sellingPrice: 5500000,
          commissionType: 'percentage',
          commissionValue: 6,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 10000000000,
          coverages: JSON.stringify([
            { title: 'آتش‌سوزی', titleEn: 'Fire', amount: 10000000000, description: 'پوشش کامل آتش' },
            { title: 'زلزله', titleEn: 'Earthquake', amount: 5000000000, description: 'پوشش زلزله' },
            { title: 'سیل', titleEn: 'Flood', amount: 5000000000, description: 'پوشش سیل' },
            { title: 'تخریب تجهیزات', titleEn: 'Equipment damage', amount: 3000000000, description: 'خسارت تجهیزات' },
          ]),
          minAge: 18,
          maxAge: 80,
          sortOrder: 2,
        },

        // ── Life Insurance ──
        {
          providerId: parsian.id,
          categoryId: life.id,
          name: 'بیمه عمر زمانی ۵ ساله',
          nameEn: '5-Year Term Life Insurance',
          description: 'پوشش فوت در مدت ۵ سال با حق بیمه پایین',
          descriptionEn: '5-year death coverage with low premium',
          basePrice: 2000000,
          sellingPrice: 2200000,
          commissionType: 'percentage',
          commissionValue: 5,
          durationDays: 1825,
          durationLabel: '5 ساله',
          durationLabelEn: '5 Years',
          coverageAmount: 1000000000,
          coverages: JSON.stringify([
            { title: 'پوشش فوت', titleEn: 'Death benefit', amount: 1000000000, description: 'مبلغ ۱ میلیارد تومان' },
            { title: 'نقص عضو ناشی از حادثه', titleEn: 'Accidental disability', amount: 500000000, description: 'تا ۵۰۰ میلیون' },
          ]),
          minAge: 18,
          maxAge: 55,
          sortOrder: 1,
        },
        {
          providerId: iran.id,
          categoryId: life.id,
          name: 'بیمه عمر کامل',
          nameEn: 'Whole Life Insurance',
          description: 'پوشش مادام‌العمر + پس‌انداز و سرمایه‌گذاری',
          descriptionEn: 'Lifetime coverage + savings and investment',
          basePrice: 8000000,
          sellingPrice: 8500000,
          commissionType: 'percentage',
          commissionValue: 4,
          durationDays: 3650,
          durationLabel: '10 ساله',
          durationLabelEn: '10 Years',
          coverageAmount: 5000000000,
          coverages: JSON.stringify([
            { title: 'پوشش فوت', titleEn: 'Death benefit', amount: 5000000000, description: 'مبلغ ۵ میلیارد' },
            { title: 'سرمایه‌گذاری', titleEn: 'Investment return', amount: 0, description: 'حداقل ۱۸٪ سود سالانه' },
            { title: 'نقص عضو', titleEn: 'Disability', amount: 2000000000, description: 'تا ۲ میلیارد' },
            { title: 'بیماری‌های خاص', titleEn: 'Critical illness', amount: 1000000000, description: 'تا ۱ میلیارد' },
          ]),
          minAge: 18,
          maxAge: 50,
          sortOrder: 2,
        },

        // ── Liability Insurance ──
        {
          providerId: alborz.id,
          categoryId: liability.id,
          name: 'بیمه مسئولیت حرفه‌ای',
          nameEn: 'Professional Liability Insurance',
          description: 'پوشش مسئولیت حرفه‌ای برای پزشکان، مهندسان و وکلا',
          descriptionEn: 'Professional liability for doctors, engineers, lawyers',
          basePrice: 5000000,
          sellingPrice: 5500000,
          commissionType: 'percentage',
          commissionValue: 4.5,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 2000000000,
          coverages: JSON.stringify([
            { title: 'خطای حرفه‌ای', titleEn: 'Professional error', amount: 1000000000, description: 'جبران خطای حرفه‌ای' },
            { title: 'غفلت', titleEn: 'Negligence', amount: 500000000, description: 'پوشش غفلت' },
            { title: 'هزینه‌های حقوقی', titleEn: 'Legal expenses', amount: 200000000, description: 'تا ۲۰۰ میلیون' },
          ]),
          minAge: 21,
          maxAge: 70,
          sortOrder: 1,
        },
        {
          providerId: parsian.id,
          categoryId: liability.id,
          name: 'بیمه مسئولیت کارفرما',
          nameEn: 'Employer Liability Insurance',
          description: 'پوشش مسئولیت کارفرما در قبال کارکنان',
          descriptionEn: 'Employer liability coverage towards employees',
          basePrice: 3000000,
          sellingPrice: 3300000,
          commissionType: 'percentage',
          commissionValue: 5,
          durationDays: 365,
          durationLabel: '1 ساله',
          durationLabelEn: '1 Year',
          coverageAmount: 1000000000,
          coverages: JSON.stringify([
            { title: 'حوادث کاری', titleEn: 'Work accidents', amount: 500000000, description: 'پوشش حوادث' },
            { title: 'بیماری‌های شغلی', titleEn: 'Occupational diseases', amount: 300000000, description: 'پوشش بیماری‌ها' },
            { title: 'هزینه پزشکی', titleEn: 'Medical costs', amount: 200000000, description: 'تا ۲۰۰ میلیون' },
          ]),
          minAge: 21,
          maxAge: 70,
          sortOrder: 2,
        },
      ],
    })

    return NextResponse.json({
      success: true,
      message: 'داده‌های آزمایشی بیمه با موفقیت ایجاد شدند',
      seeded: true,
      stats: {
        providers: providers.count,
        categories: categories.count,
        plans: plans.count,
      },
    })
  } catch (error) {
    console.error('[Insurance Seed GET]', error)
    return NextResponse.json(
      { success: false, message: 'خطا در ایجاد داده‌های آزمایشی' },
      { status: 500 }
    )
  }
}
