# Generated by Django 6.0.4 on 2026-05-03 07:10

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('xpReward', models.IntegerField(default=0)),
                ('goldRewardMg', models.FloatField(default=0)),
                ('sortOrder', models.IntegerField(default=0)),
                ('isHidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gamification_achievement',
            },
        ),
        migrations.CreateModel(
            name='CashbackReward',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('rewardType', models.CharField(default='fiat', max_length=50)),
                ('rewardValue', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
                ('claimedAt', models.DateTimeField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbackRewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_cashbackreward',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('dayNumber', models.IntegerField()),
                ('rewardType', models.CharField(default='fiat', max_length=50)),
                ('rewardValue', models.FloatField(default=0)),
                ('xpEarned', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkIns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_checkin',
            },
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('predictedPrice', models.FloatField()),
                ('actualPrice', models.FloatField(blank=True, null=True)),
                ('priceDiffPercent', models.FloatField(blank=True, null=True)),
                ('xpEarned', models.IntegerField(default=0)),
                ('isCorrect', models.BooleanField(blank=True, null=True)),
                ('targetDate', models.DateTimeField()),
                ('resolvedAt', models.DateTimeField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricePredictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_priceprediction',
            },
        ),
        migrations.CreateModel(
            name='UserGamification',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('totalBadges', models.IntegerField(default=0)),
                ('currentStreak', models.IntegerField(default=0)),
                ('longestStreak', models.IntegerField(default=0)),
                ('lastCheckInAt', models.DateTimeField(blank=True, null=True)),
                ('checkInCount', models.IntegerField(default=0)),
                ('predictionScore', models.FloatField(default=0)),
                ('referralCount', models.IntegerField(default=0)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_usergamification',
            },
        ),
        migrations.CreateModel(
            name='VIPSubscription',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(default='silver', max_length=50)),
                ('startedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('autoRenew', models.BooleanField(default=False)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vipSubscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_vipsubscription',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('earnedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAchievements', to='gamification.achievement')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAchievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_userachievement',
                'unique_together': {('userId', 'achievementId')},
            },
        ),
    ]
