# Generated by Django 6.0.4 on 2026-05-03 07:44

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestMission',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('questType', models.CharField(default='daily', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('targetValue', models.FloatField(default=1)),
                ('rewardType', models.CharField(default='xp', max_length=50)),
                ('rewardValue', models.FloatField(default=0)),
                ('xpReward', models.IntegerField(default=0)),
                ('goldRewardMg', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('sortOrder', models.IntegerField(default=0)),
                ('startsAt', models.DateTimeField(blank=True, null=True)),
                ('endsAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gamification_questmission',
            },
        ),
        migrations.CreateModel(
            name='UserQuestProgress',
            fields=[
                ('id', models.CharField(default=core.utils.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('currentValue', models.FloatField(default=0)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isClaimed', models.BooleanField(default=False)),
                ('claimedAt', models.DateTimeField(blank=True, null=True)),
                ('questId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProgress', to='gamification.questmission')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questProgress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_userquestprogress',
                'unique_together': {('userId', 'questId')},
            },
        ),
    ]
